ergebnis/classy

src/Construct.php, test/Unit/ConstructTest.php
=> Enhancement: Implement construct

.php_cs, README.md, composer.json, composer.lock, src/Constructs.php, test/Fixture/ClassyWithMethodsNamedAfterKeywords/source.php, test/Fixture/ClassyWithMethodsNamedAfterKeywordsAndReturnType/source.php, test/Fixture/ClassyWithinMultipleNamespaces/source.php, test/Fixture/ClassyWithinNamespace/source.php, test/Fixture/ClassyWithinNamespaceWithBraces/source.php, test/Fixture/ClassyWithoutNamespace/source.php, test/Fixture/ClassyWithoutNamespaceAndMultiLineComments/source.php, test/Fixture/ClassyWithoutNamespaceAndSingleLineComments/source.php, test/Fixture/NoClassy/source.php, test/Fixture/NoClassyWithAnonymousClass/source.php, test/Fixture/NoClassyWithAnonymousClassAndMultiLineComments/source.php, test/Fixture/NoClassyWithAnonymousClassAndShellStyleComments/source.php, test/Fixture/NoClassyWithAnonymousClassAndSingleLineComments/source.php, test/Fixture/NoClassyWithClassKeyword/source.php, test/Unit/ConstructsTest.php, test/Unit/ProjectCodeTest.php
=> Enhancement: Allow to collect constructs from source

README.md, src/Constructs.php, src/Exception/DirectoryDoesNotExist.php, src/Exception/MultipleDefinitionsFound.php, test/Fixture/MultipleDefinitions/One/Foo.php, test/Fixture/MultipleDefinitions/Two/Foo.php, test/Fixture/Traversal/Foo.php, test/Fixture/Traversal/Foo/Bar.php, test/Fixture/Traversal/Foo/Baz.php, test/Unit/ConstructsTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php
=> Enhancement: Collect constructs from a directory

composer.json, composer.lock
=> Fix: Package name and description

.gitattributes, .github/CONTRIBUTING.md, Makefile, composer.json, composer.lock, phpbench.json, test/Bench/ClassyBench.php
This PR
Follows https://github.com/localheinz/token/pull/6.
=> Enhancement: Use phpbench/phpbench

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/localheinz/token/compare/0.2.0...0.2.2.
```
+-------------+------------------------------+--------+--------+------+-----+------------+---------------+---------------+---------------+---------------+---------+--------+----------+
| benchmark   | subject                      | groups | params | revs | its | mem_peak   | best          | mean          | mode          | worst         | stdev   | rstdev | diff     |
+-------------+------------------------------+--------+--------+------+-----+------------+---------------+---------------+---------------+---------------+---------+--------+----------+
| ClassyBench | benchBaseline                |        | []     | 10   | 1   | 5,486,272b | 29,045.600μs  | 29,045.600μs  | 29,045.600μs  | …
```
=> Fix: Update localheinz/token

test/Bench/ClassyBench.php
=> Fix: Baseline

.php_cs, composer.json, composer.lock, src/Construct.php, src/Constructs.php, src/Exception/DirectoryDoesNotExist.php, src/Exception/ExceptionInterface.php, src/Exception/MultipleDefinitionsFound.php, src/Exception/ParseError.php, test/Bench/ClassyBench.php, test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php, test/Unit/Exception/AbstractTestCase.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Unit/ProjectCodeTest.php
This PR
💁‍♂️ For reference, see https://github.com/localheinz/php-cs-fixer-config/compare/1.6.2...1.8.0.
=> Enhancement: Update localheinz/php-cs-fixer-config

README.md
=> Fix: Add credits

.php_cs, .travis.yml, composer.json, composer.lock, test/Unit/ConstructsTest.php
=> Fix: Drop support for PHP 7.0

src/Construct.php
=> Fix: DocBlock

test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php, test/Unit/Exception/AbstractTestCase.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Unit/ProjectCodeTest.php
=> Enhancement: Add return type declarations

.travis.yml, Makefile, test/AutoReview/SrcCodeTest.php, test/AutoReview/TestCodeTest.php, test/AutoReview/phpunit.xml
=> Enhancement: Extract auto-review test suite

.travis.yml, Makefile, composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/infection/infection/compare/0.7.0...0.9.3.
=>  Enhancement: Update infection/infection

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/sebastianbergmann/phpunit/compare/6.4.1...7.4.4.
=>  Enhancement: Update phpunit/phpunit

.gitattributes, .github/CONTRIBUTING.md, .travis.yml, Makefile, composer.json, composer.lock, phpstan.neon, src/Construct.php, src/Constructs.php
=> Enhancement: Require phpstan/phpstan

.editorconfig, .gitattributes
=> Fix: Remove unused entry from .gitattributes

.github/CONTRIBUTING.md
=> Fix: Add note about mutation testing

test/AutoReview/phpunit.xml, test/Unit/phpunit.xml
=> Enhancement: Run tests in random order

.gitignore, .php_cs, .travis.yml, Makefile, infection.json, phpstan.neon
=> Enhancement: Synchronize project tooling configuration with localheinz/repository

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/phpbench/phpbench/compare/0.14.0...0.15.0.
=> Enhancement: Update phpbench/phpbench

composer.json, composer.lock
This PR
💁‍♂️ For reference, see https://github.com/phpstan/phpstan/compare/0.10.5...0.10.7.
=> Enhancement: Update phpstan/phpstan

.github/settings.yml
=> Fix: Enable issues

test/Unit/ConstructsTest.php
=> Fix: Inline variable

test/Bench/ClassyBench.php, test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php
=> Fix: Add return type declarations

Makefile, composer.json, composer.lock
=> Fix: Restore bench target

phpstan.neon, src/Constructs.php, test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php
=> Enhancement: Stop ignoring issues reported via static analysis

.dependabot/config.yml, .github/CONTRIBUTING.md, .github/settings.yml, .github/workflows/continuous-integration.yml, .github/workflows/stale.yml, Makefile, README.md, composer.json, composer.lock, phpstan-baseline.neon, phpstan.neon
=> Enhancement: Synchronize project tooling configuration with ergebnis/php-library-template

.github/workflows/continuous-integration.yml, Makefile
=> Fix: Adjust MSI score

README.md
=> Fix: Code examples

.github/workflows/continuous-integration.yml, Makefile
=> Fix: Adjust MSI score requirements

.dependabot/config.yml, .github/settings.yml, .github/workflows/continuous-integration.yml, Makefile, README.md
=> Enhancement: Synchronize with ergebnis/php-library-template

.github/workflows/continuous-integration.yml
=> Fix: Directory

.github/settings.yml, README.md, composer.json
=> made the 'classy' term clearer

.github/workflows/integrate.yaml, .github/workflows/renew.yaml, composer.json, composer.lock
=> Fix: Branch alias

.github/workflows/integrate.yaml, .github/workflows/renew.yaml
This PR
💁‍♂️ For reference, see https://github.com/ergebnis/composer-root-version-action/compare/0.2.0...0.2.1.
=> Fix: Update ergebnis/composer-root-version-action

.php_cs, LICENSE.md, src/Construct.php, src/Constructs.php, src/Exception/DirectoryDoesNotExist.php, src/Exception/ExceptionInterface.php, src/Exception/MultipleDefinitionsFound.php, src/Exception/ParseError.php, src/Exception/ShouldNotHappen.php, test/AutoReview/SrcCodeTest.php, test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Unit/Exception/ShouldNotHappenTest.php
=> Enhancement: Update license year

src/Constructs.php
=> Fix: Run 'make coding-standards'

.github/workflows/triage.yaml
=> Fix: Adjust usage of octokit

test/Unit/ConstructTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Util/Helper.php
=> Enhancement: Pull in `Helper` from `ergebnis/test-util`

.github/workflows/integrate.yaml, .github/workflows/renew.yaml, Makefile, composer.json, composer.lock
=> Fix: Remove `ergebnis/test-util`

test/Unit/ConstructTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Unit/Exception/ShouldNotHappenTest.php
=> Fix: Remove useless assertions

CHANGELOG.md, psalm-baseline.xml, src/Construct.php
=> Fix: Deprecate magic method

src/Construct.php
=> Fix: Declare object as immutable

src/Constructs.php, src/Exception/ParseError.php, test/Unit/ConstructsTest.php
=> Fix: Wrapping

test/Unit/ConstructsTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Unit/Exception/ShouldNotHappenTest.php
=> Fix: Avoid unnecessary imports

psalm-baseline.xml, test/Unit/ConstructsTest.php, test/Util/Scenario.php
=> Enhancement: Extract `Scenario`

test/Unit/ConstructsTest.php, test/Util/PhpVersion.php, test/Util/Scenario.php
=> Enhancement: Implement `PhpVersion`

.github/workflows/integrate.yaml, CHANGELOG.md, Makefile, composer-require-checker.json, psalm-baseline.xml, src/Constructs.php, test/Fixture/Classy/Php81/WithMethodsNamedAfterKeywords/source.php, test/Fixture/Classy/Php81/WithMethodsNamedAfterKeywordsAndReturnType/source.php, test/Fixture/Classy/Php81/WithinMultipleNamespaces/source.php, test/Fixture/Classy/Php81/WithinNamespace/source.php, test/Fixture/Classy/Php81/WithinNamespaceAndMultiLineComments/source.php, test/Fixture/Classy/Php81/WithinNamespaceAndShellStyleComments/source.php, test/Fixture/Classy/Php81/WithinNamespaceAndSingleLineComments/source.php, test/Fixture/Classy/Php81/WithinNamespaceWithBraces/source.php, test/Fixture/Classy/Php81/WithinNamespaceWithSingleSegment/source.php, test/Fixture/Classy/Php81/WithoutNamespace/source.php, test/Unit/ConstructsTest.php, test/Util/PhpVersion.php
=> Enhancement: Add support for `enum`

.php-cs-fixer.php, src/Constructs.php, src/Exception/DirectoryDoesNotExist.php, src/Exception/MultipleDefinitionsFound.php, src/Exception/ParseError.php, test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php, test/Util/Scenario.php
=> Enhancement: Use `Php73` rule set

.php-cs-fixer.php, src/Construct.php, src/Exception/DirectoryDoesNotExist.php, src/Exception/MultipleDefinitionsFound.php, test/Unit/ConstructsTest.php, test/Util/PhpVersion.php, test/Util/Scenario.php
=> Enhancement: Use `Php74` rule set

psalm-baseline.xml, src/Exception/DirectoryDoesNotExist.php, src/Exception/MultipleDefinitionsFound.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php
=> Fix: Initialize fields

.github/workflows/integrate.yaml, .github/workflows/prune.yaml, .github/workflows/release.yaml, .github/workflows/renew.yaml
=> Enhancement: Synchronize with `ergebnis/php-package-template`

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, CHANGELOG.md, composer.json, composer.lock, infection.json, src/Constructs.php
=> Fix: Drop support for PHP 7.4

composer.json, composer.lock
=> Fix: Remove branch alias

test/Unit/ConstructsTest.php
=> Fix: Version

infection.json, test/Unit/ConstructsTest.php
=> Fix: Assert that values are lists

.github/settings.yml, .github/workflows/integrate.yaml, CHANGELOG.md, composer.json, composer.lock
This pull request
Related to #987.
=> Fix: Drop support for PHP 7.3

.github/settings.yml, .github/workflows/integrate.yaml, CHANGELOG.md, composer.json, composer.lock
=> Add support for PHP 8.4
