ergebnis/classy

test/Unit/ConstructTest.php
=> Fix: Add missing test

composer.json, composer.lock, src/Constructs.php, test/Unit/ConstructsTest.php
This PR
```
+-------------+------------------------------+--------+--------+------+-----+------------+---------------+---------------+---------------+---------------+---------+--------+----------+
| benchmark   | subject                      | groups | params | revs | its | mem_peak   | best          | mean          | mode          | worst         | stdev   | rstdev | diff     |
+-------------+------------------------------+--------+--------+------+-----+------------+---------------+---------------+---------------+---------------+---------+--------+----------+
| ClassyBench | benchBaseline                |        | []     | 10   | 1   | 5,487,504b | 28,247.100μs  | 28,247.100μs  | 28,247.100μs  | 28,247.100μs  | 0.000μs | 0.00%  | 0.00%    |
| ClassyBench | benchConstructsFromDirectory | …
```
=> Fix: Inline localheinz/token

composer.lock
This PR
Follows #12.
💁‍♂️ This downgrades `doctrine/instantiator`.
=> Fix: Update phpunit/phpunit

src/Exception/DirectoryDoesNotExist.php, src/Exception/ExceptionInterface.php, src/Exception/MultipleDefinitionsFound.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php
=> Enhancement: Have exceptions implement ExceptionInterface

src/Constructs.php, src/Exception/ParseError.php, test/Unit/ConstructsTest.php, test/Unit/Exception/AbstractTestCase.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php
=> Enhancement: Handle parse errors

src/Exception/ExceptionInterface.php
=> Fix: Extend Throwable

.travis.yml
=> Fix: Explicitly list infection stage

composer.json, composer.lock, phpstan.neon
=> Enhancement: Require phpstan/phpstan-strict-rules

composer.json, composer.lock, phpstan.neon, test/AutoReview/SrcCodeTest.php
=> Enhancement: Require localheinz/phpstan-rules

.gitignore, phpstan.neon
=> Fix: Use currentWorkingDirectory instead of rootDir for phpstan configuration

composer.json, composer.lock, phpstan.neon, test/Unit/ConstructTest.php
=> Enhancement: Require phpstan/phpstan-deprecation-rules

test/Unit/ConstructsTest.php
=> Fix: Method can be static

test/Unit/ConstructsTest.php
=> Fix: Use provide as data provider prefix

.php_cs, CHANGELOG.md, README.md, composer.json, composer.lock, src/Construct.php, src/Constructs.php, src/Exception/DirectoryDoesNotExist.php, src/Exception/ExceptionInterface.php, src/Exception/MultipleDefinitionsFound.php, src/Exception/ParseError.php, test/AutoReview/SrcCodeTest.php, test/Bench/ClassyBench.php, test/Unit/ConstructTest.php, test/Unit/ConstructsTest.php, test/Unit/Exception/AbstractTestCase.php, test/Unit/Exception/DirectoryDoesNotExistTest.php, test/Unit/Exception/MultipleDefinitionsFoundTest.php, test/Unit/Exception/ParseErrorTest.php
=> Fix: References after move to @ergebnis

composer.json, composer.lock, phpstan.neon
=> Fix: Require phpstan/extension-installer

CHANGELOG.md, composer.json, composer.lock
=> Fix: Replace localheinz/classy

.github/settings.yml, .github/workflows/continuous-integration.yml, .php_cs, CHANGELOG.md, composer.json, composer.lock, phpstan.neon
This PR
Related to https://github.com/ergebnis/composer-normalize/issues/266.
=> Fix: Bring back support for PHP 7.1

.php_cs, composer.json, composer.lock
=> Enhancement: Use ergebnis/php-cs-fixer-config instead of localheinz/php-cs-fixer-config

composer.json, composer.lock, phpstan.neon, src/Construct.php, src/Constructs.php, src/Exception/MultipleDefinitionsFound.php, src/Exception/ShouldNotHappen.php, test/Unit/ConstructsTest.php, test/Unit/Exception/ShouldNotHappenTest.php
=> Enhancement: Update phpstan/phpstan and friends

.github/workflows/continuous-integration.yml, .github/workflows/license.yml, .github/workflows/stale.yml, README.md
=> Enhancement: Synchronize with ergebnis/php-library-template

psalm.xml
=> Fix: Exclude fixtures from analysis with vimeo/psalm

Makefile
=> Fix: Export COMPOSER_ROOT_VERSION environment variable in Makefile

.github/workflows/integrate.yaml, CHANGELOG.md, Makefile, composer-require-checker.json, composer.json, composer.lock, src/Constructs.php
This PR
💁‍♂️ For reference, see https://wiki.php.net/rfc/namespaced_names_as_token.
=> Enhancement: Add support for PHP 8.0

.github/settings.yml
=> Fix: Require tests for PHP 8.0 to pass

composer.json, composer.lock
This pull request
Related to #326.
=> Fix: Use classmap autoloader for test fixtures

.github/workflows/integrate.yaml, CHANGELOG.md, Makefile, src/Constructs.php, test/Fixture/Classy/WithinNamespaceWithSingleSegment/source.php, test/Unit/ConstructsTest.php
=> Fix: Properly determine classy name within namespace with single segment

.github/workflows/merge.yaml
This pull request
Follows #432.
=> Fix: Adjust usage of `octokit`

psalm-baseline.xml, test/Unit/ConstructTest.php, test/Unit/Exception/DirectoryDoesNotExistTest.php
=> Fix: Use methods instead of deprecated magic properties

test/Unit/ConstructTest.php
=> Fix: Use `range()`

test/Unit/ConstructsTest.php
=> Fix: Use class pseudo constant

composer.json
=> Fix: Allow composer plugin

.github/workflows/integrate.yaml, Makefile, infection.json
=> Fix: Configure `infection/infection` via configuration file only

.github/settings.yml, .github/workflows/integrate.yaml, .github/workflows/renew.yaml, .php-cs-fixer.php, CHANGELOG.md, composer.json, composer.lock, infection.json, psalm-baseline.xml, rector.php, src/Constructs.php
=> Fix: Drop support for PHP 8.0

psalm-baseline.xml, src/Construct.php, src/Constructs.php, src/Exception/MultipleDefinitionsFound.php, test/Unit/ConstructsTest.php, test/Util/Scenario.php
=> Fix: Use `list` in DocBlocks
